In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
print(type(x))

<class 'numpy.ndarray'>


In [3]:
print(x.shape)

(3,)


In [5]:
print(x[0],x[1], x[2])

1 2 3


In [6]:
x[1]=5
print(x)

[1 5 3]


In [7]:
y = np.array([[1,2,3],[4,5,6]])
print(y.shape)

(2, 3)


In [9]:
print(y[0,0],y[0,1],y[1,1],y[1,2])


1 2 5 6


In [12]:
z = np.zeros((2,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
k = np.ones((2,3))
print(k)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
p = np.full((2,3),8)

print(p)


[[8 8 8]
 [8 8 8]]


In [19]:
p[1,2] = 9 
print(p)

[[8 8 8]
 [8 9 9]]


In [20]:
e = np.random.random((2,2))
print(e)

[[0.66363142 0.02710499]
 [0.52938176 0.33618518]]


In [21]:
a = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [25]:
row_r1 = a[1,:]
print(row_r1,row_r1.shape, type(row_r1))

[4 5 6] (3,) <class 'numpy.ndarray'>


In [28]:
col_r1 = a[:,1]
print(col_r1, col_r1.shape)

[2 5 8] (3,)


a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

## Create a new array from which we will select elements and update them

In [32]:
r = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(r)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [33]:
r[1,1] = 50

print(r)

[[ 1  2  3]
 [ 4 50  6]
 [ 7  8  9]
 [10 11 12]]


In [36]:
d = np.array([0,2,0,2])
print(r[np.arange(4),d])


[ 1  6  7 12]


## Boolean array indexing:Frequently this of indexing is used to select the elements of an array that satisfy some condition

In [38]:
bo = np.array([[1,2],[3,4],[5,6]])


In [47]:
bool_idx = (bo > 2) 
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [48]:
print(bo[bool_idx])

[3 4 5 6]


## Find out Datatypes

In [49]:
bo = np.array([[1,2],[3,4],[5,6]])
print(bo.dtype)

int32


In [50]:
bo = np.array([[1,2],[3,4],[5,6]])
print(bo.dtype)

int32


## Array Maths

In [51]:
x = np.array([[1,2],[3,4]])
y = np.array([[3,4],[5,6]])

In [52]:
print(x+y)

[[ 4  6]
 [ 8 10]]


In [53]:
print(x-y)

[[-2 -2]
 [-2 -2]]


In [55]:
print(np.add(x,y))

[[ 4  6]
 [ 8 10]]


In [59]:
print(np.sum(x))
print(np.sum(y))

10
18


In [60]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [61]:
print(x/y)

[[0.33333333 0.5       ]
 [0.6        0.66666667]]


In [62]:
print(x*y)

[[ 3  8]
 [15 24]]


In [69]:
print(np.multiply(x,y))
print(np.divide(x,y))
print(np.subtract(x,y))

[[ 3  8]
 [15 24]]
[[0.33333333 0.5       ]
 [0.6        0.66666667]]
[[-2 -2]
 [-2 -2]]


# We use the dot function to compute inner products of vectors

In [70]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])


In [72]:
print(v.dot(w))
print(np.dot(v,w))

219
219


In [73]:
print(x.dot(v))
print(np.dot(x,v))

[29 67]
[29 67]


In [75]:
print(x.dot(y))
print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [76]:
print(x.T)

[[1 3]
 [2 4]]


In [78]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])

In [80]:
print(x+v)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [82]:
v = np.array([1,2])
w = np.array([4,5])

print(v*w)

[ 4 10]


In [84]:
v = np.array([1,2,3])
w = np.array([4,5])

print(np.reshape(v, (3, 1))* w)

[[ 4  5]
 [ 8 10]
 [12 15]]
