In [1]:
import numpy as np

## 1. Create a null vector of size 10 but the fifth value which is 1. 
Output: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

In [2]:
x = np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 2. Create a vector with values ranging from 10 to 49.

In [4]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 3. Create a 3x3x3 array with random values. 

In [5]:
a = np.random.random((3,3,3))*100
print(a)

[[[ 7.23614229 30.23743888 57.96442051]
  [52.22532091 95.59864688 11.51154142]
  [33.99234229 78.41384725 61.15451465]]

 [[21.33025367 45.46162999 53.53409757]
  [67.70517608 45.58986797 21.77503499]
  [38.17081624 95.6533172  69.65513701]]

 [[57.01291241 64.30773436 18.87792516]
  [28.13622137 19.05235472 99.65459006]
  [ 8.68353499 60.34468834 74.52852768]]]


## 4. Create a 10x10 array with random values and find the minimum and maximum values.

In [6]:
r = np.random.random((10,10))*100
print(r.min())
print(r.max())

0.23418125726631933
99.87721211133506


## 5. Create a random vector of size 30 and find the mean value. 

In [7]:
rv = np.random.random(30)*100
print(rv.mean())


59.84003238119214


## 6. Create a 2d array with 1 on the border and 0 inside. 
Output: 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.] 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.] 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.] 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.] 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.] 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.] 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.] 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.] 
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] 

In [12]:
A2d = np.zeros((10,10))
#print(A2d)
A2d[0,:] = 1
A2d[:,0] = 1
A2d[9,:] = 1
A2d[:,9] = 1
print(A2d)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 7. Create a 8x8 matrix and fill it with a checkerboard pattern. 
Output: 
[[0 1 0 1 0 1 0 1] 
[1 0 1 0 1 0 1 0] 
[0 1 0 1 0 1 0 1] 
[1 0 1 0 1 0 1 0] 
[0 1 0 1 0 1 0 1] 
[1 0 1 0 1 0 1 0] 
[0 1 0 1 0 1 0 1] 
[1 0 1 0 1 0 1 0]] 

In [14]:
m8 = np.ones((8,8))

# m8[::2,::2]=0    # fixed the index row of 0,2,4,6  corent one /...... ... 

# m8[::2]=0 # it select the even rows and turn then 0 
# m8[1::2]=0 # it is selecting all the the odd rows and turning them 0 
# m8[1::2,1::2] = 0 # fixed the idx of row 1,3,5,7 corrent one / ..... ./. ./

m8[0::2,0::2] = 0
m8[1::2,1::2] = 0

print(m8)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## 8. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal. 
Output: 
[[0 0 0 0 0] 
[1 0 0 0 0] 
[0 2 0 0 0] 
[0 0 3 0 0] 
[0 0 0 4 0]] 

In [15]:
m5 = np.zeros((5,5))

m5[1,0] = 1
m5[2,1] = 2
m5[3,2] = 3
m5[4,3] = 4
print(m5)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


## 9. Create a random vector of size 10 and sort it. 

In [16]:
v10 = np.random.random(10)*100
print(np.sort(v10))

[ 7.23468887  7.2713039   8.17859561 14.84598567 41.94456647 49.09131207
 50.41777036 54.09150169 70.55351916 88.84237731]


## 10. Create random vector of size 10 and replace the maximum value by 0. 

In [17]:
rv10 = np.random.random(10)*100
print(rv10)
rv10[rv10.argmax()] = 0
print(rv10)

[ 6.40983691  8.99321658 85.53531306 16.91898492 75.19713915 45.42003725
 73.46093173 63.08836824 92.79804741 94.5982222 ]
[ 6.40983691  8.99321658 85.53531306 16.91898492 75.19713915 45.42003725
 73.46093173 63.08836824 92.79804741  0.        ]
